variables:
    testname: registry.gitlab.com/m.nurfaizal96/pegadaian-gitlab-cicd:$CI_COMMIT_REF_NAME

stages:
    - build
    - run

build_docker_image:
    stage: build
    script:
        - docker build -t $testname .
    tags:
        - build

run_docker_image:
    stage: run
    script:
        - docker run -d -p 1234:80 --name pegadaian $testname
    tags:
        - run